import CoreData

// These classes are normally generated by Xcode from TestigoUY.xcdatamodeld.
// Defined here manually so the project also compiles via SPM (which cannot
// process .xcdatamodeld files).

@objc(CameraEntity)
public class CameraEntity: NSManagedObject {
    @NSManaged public var id: UUID?
    @NSManaged public var name: String?
    @NSManaged public var host: String?
    @NSManaged public var rtspPort: Int32
    @NSManaged public var rtspPath: String?
    @NSManaged public var username: String?
    @NSManaged public var password: String?
    @NSManaged public var onvifPort: Int32
    @NSManaged public var ptzCapability: String?
    @NSManaged public var streamProfile: String?
    @NSManaged public var isEnabled: Bool
    @NSManaged public var recordings: NSSet?
}

@objc(RecordingEntity)
public class RecordingEntity: NSManagedObject {
    @NSManaged public var id: UUID?
    @NSManaged public var cameraName: String?
    @NSManaged public var filePath: String?
    @NSManaged public var startDate: Date?
    @NSManaged public var endDate: Date?
    @NSManaged public var fileSize: Int64
    @NSManaged public var thumbnailPath: String?
    @NSManaged public var camera: CameraEntity?
}
